# use a Node v12 based image
FROM node:12-alpine
# switch to the /app folder in the image
WORKDIR /app
# copy all files from the folder its in into the /app folder we switched to
COPY ./ ./
# launch the main.js file
CMD node main.js
